name: shot_stance_sprawl
description: Shadow wrestling drill assistant
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  ffmpeg_kit_flutter_new_min_gpl: ^2.0.0  # watermarking kit
  
  # Camera, Gallery & Files
  camera: ^0.11.0
  path_provider: ^2.1.5
  gal: ^2.3.0
  permission_handler: ^12.0.1

  #image picker
  image_picker: ^1.0.7
  
  # Persistence & Web
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.0

  # Audio
  audioplayers: ^6.5.1
  audio_session: ^0.1.25
  record: ^6.1.2

  # Firebase 
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/audio/callouts/
    - assets/images/keepkidswrestling_logo.png

   
